version: "3.6"

services:
  order:
    build:
      context: "."
      dockerfile: "./app.dockerfile"
    depends_on:
      - "order_db"
    environment:
      DATABASE_URL: "postgres://spidey:123456@order_db/spidey?sslmode=disable"
  order_db:
    build:
      context: "./order"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "spidey"
      POSTGRES_USER: "spidey"
      POSTGRES_PASSWORD: "123456"
    restart: "unless-stopped"